language: node_js
node_js:
  - 15

jobs:
  include:
    - stage: tests and code coverage
      script:
        - cd library
        - yarn run test
        - sed -i "s/\.\.\/\.\.\///g" coverage/lcov.info

before_deploy:
  - cd library
  - yarn run doc
  - touch docs/.nojekyll
  - echo $'always-auth=true\n//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc

# Only when deploying a new release
deploy:
  # Deploys package on NPM
  - provider: script
    skip_cleanup: true
    script: ls && yarn run build && sed -i "s/TRAVIS_TAG/$TRAVIS_TAG/g" ./dist/package.json && npm publish ./dist && rm .npmrc
    on:
      tags: true
  # Generates documentation
  - provider: pages
    skip_cleanup: true
    keep_history: true
    target_branch: master
    github_token: $GITHUB_TOKEN
    on:
      tags: true

# Coveralls is executed at the very end to prevent it from making deployment fail in case of error
after_success:
  - ./library/node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
